Method,Name,Error,Occurrences
GET,/fake-sqlite/add?id=0,"('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))",13
GET,/fake-sqlite/add?id=29,"HTTPConnectionPool(host='45.55.42.197', port=3000): Max retries exceeded with url: /fake-sqlite/add?id=29 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f552ec0fd30>: Failed to establish a new connection: [Errno 111] Connection refused',))",20
GET,/fake-sqlite/add?id=43,"HTTPConnectionPool(host='45.55.42.197', port=3000): Max retries exceeded with url: /fake-sqlite/add?id=43 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f553c867860>: Failed to establish a new connection: [Errno 111] Connection refused',))",1
GET,/fake-sqlite/add?id=6,"('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))",8
GET,/fake-sqlite/add?id=32,"HTTPConnectionPool(host='45.55.42.197', port=3000): Max retries exceeded with url: /fake-sqlite/add?id=32 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f553c0440b8>: Failed to establish a new connection: [Errno 111] Connection refused',))",15
GET,/fake-sqlite/add?id=2,"HTTPConnectionPool(host='45.55.42.197', port=3000): Max retries exceeded with url: /fake-sqlite/add?id=2 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f553c24be80>: Failed to establish a new connection: [Errno 111] Connection refused',))",332
GET,/fake-sqlite/add?id=14,"HTTPConnectionPool(host='45.55.42.197', port=3000): Max retries exceeded with url: /fake-sqlite/add?id=14 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f552ed4e630>: Failed to establish a new connection: [Errno 111] Connection refused',))",278
GET,/fake-sqlite/add?id=29,"('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))",1
GET,/fake-sqlite/add?id=17,"HTTPConnectionPool(host='45.55.42.197', port=3000): Max retries exceeded with url: /fake-sqlite/add?id=17 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f55345895c0>: Failed to establish a new connection: [Errno 111] Connection refused',))",206
GET,/fake-sqlite/add?id=8,"('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))",5
GET,/fake-sqlite/add?id=22,"HTTPConnectionPool(host='45.55.42.197', port=3000): Max retries exceeded with url: /fake-sqlite/add?id=22 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f552ef4eac8>: Failed to establish a new connection: [Errno 111] Connection refused',))",100
GET,/fake-sqlite/add?id=4,"HTTPConnectionPool(host='45.55.42.197', port=3000): Max retries exceeded with url: /fake-sqlite/add?id=4 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f553c1da0b8>: Failed to establish a new connection: [Errno 111] Connection refused',))",360
GET,/fake-sqlite/add?id=5,"('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))",19
GET,/fake-sqlite/add?id=1,"HTTPConnectionPool(host='45.55.42.197', port=3000): Max retries exceeded with url: /fake-sqlite/add?id=1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f553c1da160>: Failed to establish a new connection: [Errno 111] Connection refused',))",316
GET,/fake-sqlite/add?id=33,"HTTPConnectionPool(host='45.55.42.197', port=3000): Max retries exceeded with url: /fake-sqlite/add?id=33 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f552ec19080>: Failed to establish a new connection: [Errno 111] Connection refused',))",14
GET,/fake-sqlite/add?id=39,"HTTPConnectionPool(host='45.55.42.197', port=3000): Max retries exceeded with url: /fake-sqlite/add?id=39 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f55340955c0>: Failed to establish a new connection: [Errno 111] Connection refused',))",6
GET,/fake-sqlite/add?id=15,"HTTPConnectionPool(host='45.55.42.197', port=3000): Max retries exceeded with url: /fake-sqlite/add?id=15 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f552edddc18>: Failed to establish a new connection: [Errno 111] Connection refused',))",253
GET,/fake-sqlite/add?id=8,"HTTPConnectionPool(host='45.55.42.197', port=3000): Max retries exceeded with url: /fake-sqlite/add?id=8 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f553450e2e8>: Failed to establish a new connection: [Errno 111] Connection refused',))",343
GET,/fake-sqlite/add?id=0,"('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))",58
GET,/fake-sqlite/add?id=41,"HTTPConnectionPool(host='45.55.42.197', port=3000): Max retries exceeded with url: /fake-sqlite/add?id=41 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5534792dd8>: Failed to establish a new connection: [Errno 111] Connection refused',))",1
GET,/fake-sqlite/add?id=38,"HTTPConnectionPool(host='45.55.42.197', port=3000): Max retries exceeded with url: /fake-sqlite/add?id=38 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f552ec0fe10>: Failed to establish a new connection: [Errno 111] Connection refused',))",6
GET,/fake-sqlite/add?id=3,"HTTPConnectionPool(host='45.55.42.197', port=3000): Max retries exceeded with url: /fake-sqlite/add?id=3 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f553c24bc88>: Failed to establish a new connection: [Errno 111] Connection refused',))",352
GET,/fake-sqlite/add?id=10,"('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))",5
GET,/fake-sqlite/add?id=5,"HTTPConnectionPool(host='45.55.42.197', port=3000): Max retries exceeded with url: /fake-sqlite/add?id=5 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f553c24bbe0>: Failed to establish a new connection: [Errno 111] Connection refused',))",369
GET,/fake-sqlite/add?id=24,"HTTPConnectionPool(host='45.55.42.197', port=3000): Max retries exceeded with url: /fake-sqlite/add?id=24 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f552ed4e2e8>: Failed to establish a new connection: [Errno 111] Connection refused',))",73
GET,/fake-sqlite/add?id=28,"HTTPConnectionPool(host='45.55.42.197', port=3000): Max retries exceeded with url: /fake-sqlite/add?id=28 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f553c044978>: Failed to establish a new connection: [Errno 111] Connection refused',))",25
GET,/fake-sqlite/add?id=9,"('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))",8
GET,/fake-sqlite/add?id=16,"HTTPConnectionPool(host='45.55.42.197', port=3000): Max retries exceeded with url: /fake-sqlite/add?id=16 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5534483b38>: Failed to establish a new connection: [Errno 111] Connection refused',))",221
GET,/fake-sqlite/add?id=30,"HTTPConnectionPool(host='45.55.42.197', port=3000): Max retries exceeded with url: /fake-sqlite/add?id=30 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f55344834e0>: Failed to establish a new connection: [Errno 111] Connection refused',))",16
GET,/fake-sqlite/add?id=20,"HTTPConnectionPool(host='45.55.42.197', port=3000): Max retries exceeded with url: /fake-sqlite/add?id=20 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5534589828>: Failed to establish a new connection: [Errno 111] Connection refused',))",149
GET,/fake-sqlite/add?id=11,"HTTPConnectionPool(host='45.55.42.197', port=3000): Max retries exceeded with url: /fake-sqlite/add?id=11 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f553453c860>: Failed to establish a new connection: [Errno 111] Connection refused',))",314
GET,/fake-sqlite/add?id=7,"HTTPConnectionPool(host='45.55.42.197', port=3000): Max retries exceeded with url: /fake-sqlite/add?id=7 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f55344726a0>: Failed to establish a new connection: [Errno 111] Connection refused',))",361
GET,/fake-sqlite/add?id=14,"('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))",1
GET,/fake-sqlite/add?id=27,"HTTPConnectionPool(host='45.55.42.197', port=3000): Max retries exceeded with url: /fake-sqlite/add?id=27 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f55342952e8>: Failed to establish a new connection: [Errno 111] Connection refused',))",38
GET,/fake-sqlite/add?id=13,"('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))",4
GET,/fake-sqlite/add?id=34,"HTTPConnectionPool(host='45.55.42.197', port=3000): Max retries exceeded with url: /fake-sqlite/add?id=34 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f55344e86d8>: Failed to establish a new connection: [Errno 111] Connection refused',))",13
GET,/fake-sqlite/add?id=9,"HTTPConnectionPool(host='45.55.42.197', port=3000): Max retries exceeded with url: /fake-sqlite/add?id=9 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f553453c518>: Failed to establish a new connection: [Errno 111] Connection refused',))",332
GET,/fake-sqlite/add?id=23,"('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))",1
GET,/fake-sqlite/add?id=40,"HTTPConnectionPool(host='45.55.42.197', port=3000): Max retries exceeded with url: /fake-sqlite/add?id=40 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f553431a6d8>: Failed to establish a new connection: [Errno 111] Connection refused',))",3
GET,/fake-sqlite/add?id=12,"('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))",5
GET,/fake-sqlite/add?id=4,"('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))",27
GET,/fake-sqlite/add?id=3,"('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))",25
GET,/fake-sqlite/add?id=12,"HTTPConnectionPool(host='45.55.42.197', port=3000): Max retries exceeded with url: /fake-sqlite/add?id=12 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5534589780>: Failed to establish a new connection: [Errno 111] Connection refused',))",305
GET,/fake-sqlite/add?id=25,"HTTPConnectionPool(host='45.55.42.197', port=3000): Max retries exceeded with url: /fake-sqlite/add?id=25 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f552eddd898>: Failed to establish a new connection: [Errno 111] Connection refused',))",60
GET,/fake-sqlite/add?id=36,"HTTPConnectionPool(host='45.55.42.197', port=3000): Max retries exceeded with url: /fake-sqlite/add?id=36 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f553c78b400>: Failed to establish a new connection: [Errno 111] Connection refused',))",8
GET,/fake-sqlite/add?id=42,"HTTPConnectionPool(host='45.55.42.197', port=3000): Max retries exceeded with url: /fake-sqlite/add?id=42 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f553c45e518>: Failed to establish a new connection: [Errno 111] Connection refused',))",1
GET,/fake-sqlite/add?id=6,"HTTPConnectionPool(host='45.55.42.197', port=3000): Max retries exceeded with url: /fake-sqlite/add?id=6 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f553c0a3048>: Failed to establish a new connection: [Errno 111] Connection refused',))",372
GET,/fake-sqlite/add?id=19,"HTTPConnectionPool(host='45.55.42.197', port=3000): Max retries exceeded with url: /fake-sqlite/add?id=19 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f55344837f0>: Failed to establish a new connection: [Errno 111] Connection refused',))",167
GET,/fake-sqlite/add?id=2,"('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))",28
GET,/fake-sqlite/add?id=16,"('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))",3
GET,/fake-sqlite/add?id=18,"HTTPConnectionPool(host='45.55.42.197', port=3000): Max retries exceeded with url: /fake-sqlite/add?id=18 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5534250a90>: Failed to establish a new connection: [Errno 111] Connection refused',))",188
GET,/fake-sqlite/add?id=20,"('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))",1
GET,/fake-sqlite/add?id=10,"HTTPConnectionPool(host='45.55.42.197', port=3000): Max retries exceeded with url: /fake-sqlite/add?id=10 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f553c838b38>: Failed to establish a new connection: [Errno 111] Connection refused',))",322
GET,/fake-sqlite/add?id=0,"HTTPConnectionPool(host='45.55.42.197', port=3000): Max retries exceeded with url: /fake-sqlite/add?id=0 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f552ee66e10>: Failed to establish a new connection: [Errno 111] Connection refused',))",253
GET,/fake-sqlite/add?id=23,"HTTPConnectionPool(host='45.55.42.197', port=3000): Max retries exceeded with url: /fake-sqlite/add?id=23 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f552ef76cc0>: Failed to establish a new connection: [Errno 111] Connection refused',))",80
GET,/fake-sqlite/add?id=44,"HTTPConnectionPool(host='45.55.42.197', port=3000): Max retries exceeded with url: /fake-sqlite/add?id=44 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5534174eb8>: Failed to establish a new connection: [Errno 111] Connection refused',))",1
GET,/fake-sqlite/add?id=21,"HTTPConnectionPool(host='45.55.42.197', port=3000): Max retries exceeded with url: /fake-sqlite/add?id=21 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f55344836a0>: Failed to establish a new connection: [Errno 111] Connection refused',))",125
GET,/fake-sqlite/add?id=25,"('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))",1
GET,/fake-sqlite/add?id=1,"('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))",29
GET,/fake-sqlite/add?id=35,"HTTPConnectionPool(host='45.55.42.197', port=3000): Max retries exceeded with url: /fake-sqlite/add?id=35 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f553c32df60>: Failed to establish a new connection: [Errno 111] Connection refused',))",10
GET,/fake-sqlite/add?id=11,"('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))",5
GET,/fake-sqlite/add?id=15,"('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))",1
GET,/fake-sqlite/add?id=19,"('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))",2
GET,/fake-sqlite/add?id=7,"('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))",5
GET,/fake-sqlite/add?id=37,"HTTPConnectionPool(host='45.55.42.197', port=3000): Max retries exceeded with url: /fake-sqlite/add?id=37 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f55347937b8>: Failed to establish a new connection: [Errno 111] Connection refused',))",7
GET,/fake-sqlite/add?id=31,"HTTPConnectionPool(host='45.55.42.197', port=3000): Max retries exceeded with url: /fake-sqlite/add?id=31 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5534295048>: Failed to establish a new connection: [Errno 111] Connection refused',))",16
GET,/fake-sqlite/add?id=26,"HTTPConnectionPool(host='45.55.42.197', port=3000): Max retries exceeded with url: /fake-sqlite/add?id=26 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5534483748>: Failed to establish a new connection: [Errno 111] Connection refused',))",46
GET,/fake-sqlite/add?id=13,"HTTPConnectionPool(host='45.55.42.197', port=3000): Max retries exceeded with url: /fake-sqlite/add?id=13 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f5534589630>: Failed to establish a new connection: [Errno 111] Connection refused',))",294
GET,/fake-sqlite/add?id=18,"('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))",2
